import { StyleSheet } from 'react-native';
import { PRIMARY, PAGE_BG } from '../ClienteHome/styles';

export { GOLD, PRIMARY, PAGE_BG } from '../ClienteHome/styles';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: PAGE_BG,
  },
  header: {
    backgroundColor: PRIMARY,
    paddingHorizontal: 20,
    paddingBottom: 28,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  brandQuick: {
    color: '#FFF',
    fontSize: 22,
    fontWeight: '800',
  },
  brandStock: {
    color: '#1F2937',
    fontSize: 22,
    fontWeight: '800',
  },
  bellButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  title: {
    color: '#FFF',
    fontSize: 32,
    fontWeight: '800',
    marginBottom: 6,
  },
  subtitle: {
    color: 'rgba(255,255,255,0.78)',
    fontSize: 15,
  },
  sheet: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  sellerCard: {
    backgroundColor: '#FFF',
    borderRadius: 22,
    padding: 16,
    marginBottom: 12,
  },
  sellerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
  },
  sellerLogo: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#EEF2F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sellerCopy: {
    flex: 1,
  },
  sellerKicker: {
    fontSize: 12,
    color: '#8A93A3',
    fontWeight: '600',
  },
  sellerName: {
    fontSize: 16,
    fontWeight: '800',
    color: PRIMARY,
  },
  itemRow: {
    flexDirection: 'row',
    gap: 10,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#F0F2F6',
  },
  itemImage: {
    width: 52,
    height: 52,
    borderRadius: 12,
    backgroundColor: '#F5F5F5',
  },
  itemBody: {
    flex: 1,
  },
  itemTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  itemName: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    color: '#1F2937',
  },
  trashBtn: {
    padding: 2,
  },
  itemUnit: {
    fontSize: 12,
    color: '#8A93A3',
    marginTop: 2,
    marginBottom: 8,
  },
  itemBottom: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  itemPrice: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1F2937',
  },
  stepper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  stepperBtn: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#EEF2F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperValue: {
    minWidth: 18,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '800',
    color: PRIMARY,
  },
  itemSubtotal: {
    fontSize: 14,
    fontWeight: '800',
    color: PRIMARY,
    marginLeft: 8,
  },
  addressCard: {
    backgroundColor: '#FFF',
    borderRadius: 22,
    padding: 16,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  addressIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#EEF2F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  addressCopy: {
    flex: 1,
  },
  addressTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: PRIMARY,
  },
  addressHint: {
    fontSize: 12,
    color: '#8A93A3',
    marginTop: 2,
  },
  summaryCard: {
    backgroundColor: '#FFF',
    borderRadius: 22,
    padding: 16,
    marginBottom: 12,
  },
  summaryTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: PRIMARY,
    marginBottom: 12,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  summaryLabel: {
    fontSize: 14,
    color: '#6B7280',
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1F2937',
  },
  summaryTotalRow: {
    borderTopWidth: 1,
    borderTopColor: '#F0F2F6',
    paddingTop: 10,
    marginTop: 4,
    marginBottom: 0,
  },
  summaryTotalLabel: {
    fontSize: 16,
    fontWeight: '800',
    color: PRIMARY,
  },
  summaryTotalValue: {
    fontSize: 18,
    fontWeight: '800',
    color: PRIMARY,
  },
  checkoutBtn: {
    backgroundColor: '#F8B125',
    borderRadius: 22,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 8,
  },
  checkoutBtnDisabled: {
    opacity: 0.6,
  },
  checkoutText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '800',
  },
  errorText: {
    color: '#C62828',
    fontSize: 13,
    marginBottom: 8,
    textAlign: 'center',
  },
  successText: {
    color: '#2E7D32',
    fontSize: 13,
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyCard: {
    backgroundColor: '#FFF',
    borderRadius: 24,
    paddingVertical: 36,
    paddingHorizontal: 22,
    alignItems: 'center',
    minHeight: 280,
    justifyContent: 'center',
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: PRIMARY,
    textAlign: 'center',
    marginBottom: 8,
    marginTop: 12,
  },
  emptyText: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 22,
    maxWidth: 260,
  },
  cta: {
    backgroundColor: '#F8B125',
    borderRadius: 22,
    paddingVertical: 12,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  ctaText: {
    color: '#FFF',
    fontSize: 15,
    fontWeight: '800',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 32,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: PRIMARY,
    marginBottom: 16,
  },
  modalItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F2F6',
  },
  modalItemSelected: {
    backgroundColor: '#FFF8E8',
    marginHorizontal: -8,
    paddingHorizontal: 8,
    borderRadius: 12,
    borderBottomWidth: 0,
  },
  modalApelido: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1F2937',
  },
  modalResumo: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 2,
  },
  modalClose: {
    alignItems: 'center',
    paddingVertical: 14,
    marginTop: 8,
  },
  modalCloseText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#6B7280',
  },
  modalAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 12,
  },
  modalAddBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#F8B125',
  },
});
