import { StyleSheet } from 'react-native';
import { COMPANY_COLORS } from '../../theme/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAFA',
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 16,
    paddingBottom: 32,
  },
  summaryCard: {
    backgroundColor: '#FFF',
    borderRadius: 18,
    padding: 18,
    alignItems: 'center',
    marginTop: 8,
    borderWidth: 1,
    borderColor: COMPANY_COLORS.primaryBorder,
  },
  summaryValue: {
    color: COMPANY_COLORS.primary,
    fontWeight: '800',
    fontSize: 32,
  },
  summaryLabel: {
    color: '#666',
    fontSize: 13,
    marginTop: 4,
  },
  summarySub: {
    marginTop: 6,
    color: '#333',
    fontSize: 12,
  },
  formCard: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 16,
    marginTop: 18,
    borderWidth: 1,
    borderColor: COMPANY_COLORS.primaryBorder,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
  },
  listCard: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 16,
    marginTop: 18,
    borderWidth: 1,
    borderColor: COMPANY_COLORS.primaryBorder,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#222',
    marginBottom: 12,
  },
  label: {
    color: '#555',
    fontSize: 12,
    marginBottom: 6,
    marginTop: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: '#E8E8E8',
    borderRadius: 12,
    backgroundColor: '#FFF',
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: '#222',
  },
  button: {
    marginTop: 18,
    backgroundColor: COMPANY_COLORS.primary,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  buttonText: {
    color: '#FFF',
    fontWeight: '800',
    fontSize: 14,
  },
  motoristaCard: {
    backgroundColor: '#FFF9EC',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#F3CF82',
    marginTop: 12,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  motoristaNome: {
    color: '#222',
    fontSize: 16,
    fontWeight: '800',
  },
  vehicleTag: {
    color: '#A66B00',
    fontSize: 11,
    fontWeight: '700',
    backgroundColor: '#FFF0C7',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  rotaText: {
    marginTop: 8,
    color: '#555',
    fontSize: 12,
  },
  entregasList: {
    marginTop: 12,
    gap: 8,
  },
  entregaItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: COMPANY_COLORS.primary,
    marginTop: 6,
    marginRight: 10,
  },
  entregaInfo: {
    flex: 1,
  },
  entregaCliente: {
    color: '#222',
    fontWeight: '700',
    fontSize: 13,
  },
  entregaMeta: {
    color: '#666',
    fontSize: 11,
    marginTop: 2,
  },
  entregaStatus: {
    marginTop: 4,
    color: '#2DBE6A',
    fontSize: 11,
    fontWeight: '700',
  },
  semEntrega: {
    marginTop: 8,
    color: '#777',
    fontSize: 12,
  },
});
