import { StyleSheet } from 'react-native';
import {
  CARD_GAP,
  FEATURED_HEIGHT,
  FEATURED_WIDTH,
  H_PADDING,
  PARTNER_CARD_WIDTH,
  PARTNER_COVER_HEIGHT,
  SECTION_INSET,
} from './cartLayout';
import { COMPANY_COLORS } from '../../theme/theme';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#FAFAFA' },
  container: { flex: 1, backgroundColor: '#FAFAFA' },
  scrollView: { flex: 1 },
  scrollContent: { flexGrow: 1 },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    marginHorizontal: 15,
    marginTop: 8,
    marginBottom: 16,
    paddingHorizontal: 12,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#F0E6CC',
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    fontSize: 14,
    color: '#333',
    paddingVertical: 0,
  },
  successBanner: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    backgroundColor: '#E8F5E9', marginHorizontal: 15, marginBottom: 10,
    padding: 12, borderRadius: 12, borderWidth: 1, borderColor: '#A5D6A7',
  },
  successBannerText: { color: '#2E7D32', flex: 1, marginRight: 8 },
  coverFrame: {
    overflow: 'hidden',
    backgroundColor: '#E8E8E8',
    position: 'relative',
  },
  coverImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  featuredSection: {
    marginBottom: 0,
  },
  featuredScroll: {
    height: FEATURED_HEIGHT,
    overflow: 'hidden',
  },
  featuredListPadding: {
    paddingRight: 4,
    alignItems: 'flex-start',
  },
  featuredItemWrap: {
    width: FEATURED_WIDTH,
    height: FEATURED_HEIGHT,
    marginRight: CARD_GAP,
  },
  featuredItemWrapLast: {
    marginRight: 0,
  },
  featuredCard: {
    width: FEATURED_WIDTH,
    height: FEATURED_HEIGHT,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: '#E8E8E8',
    position: 'relative',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.14,
    shadowRadius: 6,
  },
  featuredOverlay: {
    ...StyleSheet.absoluteFillObject,
    pointerEvents: 'none',
  },
  featuredFooter: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  featuredLogo: {
    borderWidth: 2,
    borderColor: '#FFF',
    backgroundColor: '#FFF',
  },
  featuredTextWrap: {
    flex: 1,
    marginLeft: 10,
    marginRight: 8,
  },
  featuredTitle: {
    color: '#FFF',
    fontSize: 17,
    fontWeight: 'bold',
  },
  featuredSubtitle: {
    color: 'rgba(255,255,255,0.92)',
    fontSize: 12,
    marginTop: 2,
  },
  featuredBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
    gap: 2,
  },
  featuredBadgeText: {
    color: '#333',
    fontSize: 11,
    fontWeight: '600',
  },
  partnerListPadding: {
    paddingRight: 4,
    paddingBottom: 4,
    alignItems: 'flex-start',
  },
  partnerCard: {
    width: PARTNER_CARD_WIDTH,
    marginRight: CARD_GAP,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: COMPANY_COLORS.primarySoft,
    borderWidth: 1,
    borderColor: COMPANY_COLORS.primaryBorder,
    flexShrink: 0,
    alignSelf: 'flex-start',
  },
  partnerCoverWrap: {
    width: PARTNER_CARD_WIDTH,
    height: PARTNER_COVER_HEIGHT,
    backgroundColor: '#E8E8E8',
    overflow: 'hidden',
    position: 'relative',
  },
  partnerCoverGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  partnerBody: {
    paddingHorizontal: 12,
    paddingTop: 22,
    paddingBottom: 12,
    minHeight: 96,
  },
  partnerLogo: {
    position: 'absolute',
    top: -21,
    left: 12,
    borderWidth: 2,
    borderColor: '#FFF',
    backgroundColor: '#FFF',
  },
  partnerName: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#222',
    marginBottom: 4,
    lineHeight: 17,
  },
  partnerMeta: {
    fontSize: 11,
    color: '#777',
  },
  sectionCard: {
    backgroundColor: '#FFF',
    marginHorizontal: H_PADDING,
    marginBottom: 16,
    borderRadius: 20,
    padding: SECTION_INSET,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
  },
  sectionHeader: {
    marginBottom: 14,
  },
  section: { marginBottom: 20 },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COMPANY_COLORS.primary,
  },
  sectionSubtitle: {
    marginTop: 4,
    fontSize: 12,
    color: '#888',
  },
  emptyText: { color: '#666', fontSize: 13 },
  emptyBox: { alignItems: 'center', paddingVertical: 8 },
  errorText: { color: '#D64545', textAlign: 'center', marginBottom: 8 },
  retryText: { color: COMPANY_COLORS.primary, fontWeight: '600' },
  requestCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COMPANY_COLORS.primarySoft,
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COMPANY_COLORS.primaryBorder,
  },
  requestLogo: {
    marginRight: 10,
    borderWidth: 1,
    borderColor: COMPANY_COLORS.primaryBorder,
    backgroundColor: '#FFF',
  },
  requestCopy: {
    flex: 1,
  },
  requestTitle: {
    color: '#333',
    fontWeight: '700',
    fontSize: 13,
  },
  requestHint: {
    marginTop: 2,
    color: '#999',
    fontSize: 11,
  },
  requestCardLast: {
    marginBottom: 0,
  },
  storeCard: {
    backgroundColor: COMPANY_COLORS.primarySoft,
    borderWidth: 1,
    borderColor: COMPANY_COLORS.primaryBorder,
    borderRadius: 16,
    marginBottom: 12,
    overflow: 'hidden',
  },
  storeCoverWrap: {
    width: '100%',
    height: 96,
    backgroundColor: '#E8E8E8',
    overflow: 'hidden',
    position: 'relative',
  },
  storeContent: {
    padding: 14,
  },
  storeHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  storeLogo: {
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#F0E6CC',
  },
  storeTextContainer: { flex: 1, justifyContent: 'center', marginRight: 4 },
  storeName: { fontSize: 14, fontWeight: '700', color: '#333' },
  ratingContainer: { flexDirection: 'row', alignItems: 'center', marginTop: 2, marginBottom: 2 },
  ratingText: { fontSize: 12, fontWeight: 'bold', color: '#000', marginLeft: 4, marginRight: 4 },
  reviewsText: { fontSize: 11, color: '#666' },
  deliveryText: { fontSize: 11, color: '#333', marginTop: 8 },
  bottomBar: {
    position: 'absolute', bottom: 0, left: 0, right: 0, height: 70,
    backgroundColor: COMPANY_COLORS.primary, flexDirection: 'row', justifyContent: 'space-between',
    alignItems: 'center', paddingHorizontal: 15, borderTopLeftRadius: 15, borderTopRightRadius: 15,
  },
  tabItem: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  floatingButtonContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  floatingButton: {
    width: 76, height: 76, borderRadius: 38, backgroundColor: '#FFF',
    justifyContent: 'center', alignItems: 'center', position: 'absolute', bottom: -15,
    borderWidth: 2, borderColor: COMPANY_COLORS.primary, elevation: 6,
  },
});
