import { StyleSheet } from 'react-native';
import { CLIENTE_COLORS } from '../../theme/theme';

export const styles = StyleSheet.create({
  addButton: {
    marginHorizontal: 15,
    marginBottom: 16,
  },
  sectionCard: {
    backgroundColor: '#FFF',
    marginHorizontal: 15,
    marginBottom: 16,
    borderRadius: 20,
    padding: 16,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
  },
  sectionHeader: {
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#F8B125',
  },
  sectionSubtitle: {
    marginTop: 4,
    fontSize: 12,
    color: '#888',
  },
  enderecoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFDF7',
    borderRadius: 16,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#F3E3B1',
  },
  cardLast: {
    marginBottom: 0,
  },
  enderecoIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFF6DE',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  enderecoInfo: {
    flex: 1,
    marginRight: 8,
  },
  enderecoApelido: {
    fontSize: 14,
    fontWeight: '700',
    color: '#333',
  },
  enderecoResumo: {
    fontSize: 12,
    color: '#666',
    marginTop: 4,
    lineHeight: 17,
  },
  enderecoCep: {
    fontSize: 11,
    color: '#888',
    marginTop: 4,
  },
  principalPill: {
    alignSelf: 'flex-start',
    marginTop: 8,
    backgroundColor: '#FFF6DE',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: '#F3E3B1',
  },
  enderecoPrincipal: {
    fontSize: 11,
    fontWeight: '700',
    color: '#F8B125',
  },
  emptyIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFF6DE',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginBottom: 10,
  },
  emptyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#333',
    textAlign: 'center',
  },
  emptyText: {
    fontSize: 12,
    color: '#888',
    textAlign: 'center',
    marginTop: 6,
    lineHeight: 18,
  },
  errorText: {
    color: '#D64545',
    fontSize: 14,
    textAlign: 'center',
  },
  retryText: {
    color: '#F8B125',
    fontWeight: '600',
    marginTop: 10,
    textAlign: 'center',
  },
});

const PRIMARY = CLIENTE_COLORS.primary;
const GOLD = '#F8B125';
const PAGE_BG = '#F3F5F8';

export const clienteStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: PAGE_BG,
  },
  header: {
    backgroundColor: PRIMARY,
    paddingHorizontal: 20,
    paddingBottom: 22,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  brandRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'center',
  },
  brandQuick: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: '800',
  },
  brandStock: {
    color: '#1F2937',
    fontSize: 20,
    fontWeight: '800',
  },
  title: {
    color: '#FFF',
    fontSize: 24,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 6,
  },
  subtitle: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
  },
  sheet: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  addButton: {
    backgroundColor: GOLD,
    borderRadius: 16,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 14,
  },
  addButtonText: {
    color: '#FFF',
    fontSize: 15,
    fontWeight: '800',
  },
  emptyCard: {
    backgroundColor: '#FFF',
    borderRadius: 22,
    paddingVertical: 28,
    paddingHorizontal: 20,
    alignItems: 'center',
    marginBottom: 12,
  },
  illustration: {
    width: 220,
    height: 140,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  illustrationBg: {
    position: 'absolute',
    width: 180,
    height: 90,
    borderRadius: 20,
    backgroundColor: '#EAF1FA',
  },
  pinWrap: {
    position: 'absolute',
    top: 12,
    alignItems: 'center',
  },
  emptyTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: '#1F2937',
    textAlign: 'center',
    marginTop: 8,
  },
  emptyText: {
    fontSize: 13,
    color: '#8A93A3',
    textAlign: 'center',
    lineHeight: 19,
    marginTop: 8,
    maxWidth: 260,
  },
  infoCard: {
    backgroundColor: '#FFF',
    borderRadius: 22,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  infoIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#EAF1FA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoText: {
    flex: 1,
    fontSize: 13,
    color: '#6B7280',
    lineHeight: 18,
  },
  listCard: {
    backgroundColor: '#FFF',
    borderRadius: 22,
    padding: 8,
    marginBottom: 12,
  },
  enderecoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    gap: 10,
  },
  enderecoIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#EEF2F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  enderecoInfo: {
    flex: 1,
  },
  enderecoApelido: {
    fontSize: 15,
    fontWeight: '800',
    color: PRIMARY,
  },
  enderecoResumo: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 2,
  },
  principalPill: {
    alignSelf: 'flex-start',
    marginTop: 6,
    backgroundColor: '#EEF2F7',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  principalText: {
    fontSize: 11,
    fontWeight: '700',
    color: PRIMARY,
  },
  errorText: {
    color: '#C62828',
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 8,
  },
  retryText: {
    color: GOLD,
    fontWeight: '700',
    textAlign: 'center',
  },
});
