import { StyleSheet } from 'react-native';
import { GOLD, GREEN, PRIMARY, PAGE_BG } from '../ClienteHome/styles';

export { GOLD, GREEN, PRIMARY, PAGE_BG };

export const clienteQuiosqueStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: PAGE_BG,
  },
  header: {
    backgroundColor: PRIMARY,
    paddingHorizontal: 16,
    paddingBottom: 14,
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  headerSide: {
    width: 36,
    alignItems: 'center',
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  brandQuick: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: '800',
  },
  brandStock: {
    color: '#1F2937',
    fontSize: 20,
    fontWeight: '800',
  },
  searchBox: {
    height: 42,
    backgroundColor: '#FFF',
    borderRadius: 21,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    fontSize: 14,
    color: '#333',
    paddingVertical: 0,
  },
  banner: {
    height: 168,
    backgroundColor: PRIMARY,
    overflow: 'hidden',
  },
  bannerImage: {
    width: '100%',
    height: '100%',
  },
  bannerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(10, 24, 52, 0.28)',
    justifyContent: 'flex-end',
    padding: 16,
    paddingBottom: 36,
  },
  bannerSlogan: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: '800',
    maxWidth: 210,
    lineHeight: 26,
  },
  sheet: {
    marginTop: -22,
    backgroundColor: PAGE_BG,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 16,
    paddingTop: 44,
    minHeight: 420,
    position: 'relative',
  },
  logo: {
    position: 'absolute',
    top: -36,
    alignSelf: 'center',
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: PRIMARY,
    borderWidth: 4,
    borderColor: '#FFF',
  },
  storeTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: PRIMARY,
    textAlign: 'center',
    marginBottom: 6,
  },
  storeDesc: {
    fontSize: 13,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 12,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  metaText: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '600',
  },
  openBadge: {
    backgroundColor: '#E7F8EE',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  openText: {
    color: GREEN,
    fontSize: 11,
    fontWeight: '700',
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  stat: {
    alignItems: 'center',
    flex: 1,
  },
  statLabel: {
    marginTop: 4,
    fontSize: 11,
    color: '#6B7280',
    textAlign: 'center',
    fontWeight: '600',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1F2937',
    marginBottom: 10,
  },
  chipsRow: {
    flexDirection: 'row',
    gap: 8,
    paddingBottom: 14,
  },
  chip: {
    paddingHorizontal: 14,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#EEF2F7',
    justifyContent: 'center',
  },
  chipActive: {
    backgroundColor: PRIMARY,
  },
  chipText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#6B7280',
  },
  chipTextActive: {
    color: '#FFF',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  productCard: {
    width: '31.5%',
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 8,
    marginBottom: 12,
  },
  productImage: {
    width: '100%',
    height: 78,
    borderRadius: 10,
    backgroundColor: '#F3F5F8',
    marginBottom: 6,
  },
  productName: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1F2937',
    minHeight: 30,
  },
  productUnit: {
    fontSize: 10,
    color: '#8A93A3',
    marginBottom: 4,
  },
  productFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  productPrice: {
    fontSize: 11,
    fontWeight: '800',
    color: PRIMARY,
    flex: 1,
  },
  addButton: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stockLabel: {
    marginTop: 3,
    fontSize: 9,
    color: GREEN,
    fontWeight: '600',
  },
  empty: {
    color: '#6B7280',
    fontSize: 13,
    textAlign: 'center',
    paddingVertical: 16,
  },
  cartBar: {
    marginHorizontal: 16,
    marginBottom: 8,
    backgroundColor: GOLD,
    borderRadius: 22,
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
  },
  cartBarLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cartBarText: {
    color: '#FFF',
    fontSize: 15,
    fontWeight: '800',
  },
  cartBarCount: {
    color: '#FFF',
    fontSize: 13,
    fontWeight: '700',
  },
});
