import { StyleSheet } from 'react-native';
import { COMPANY_COLORS } from '../../theme/theme';

const ACCENT = COMPANY_COLORS.primary;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAFA',
  },
  scrollContent: {
    paddingBottom: 130,
    paddingHorizontal: 16,
  },
  heroCard: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: COMPANY_COLORS.primaryBorder,
    marginBottom: 14,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
  },
  imageWrap: {
    height: 220,
    backgroundColor: '#F5F5F5',
    overflow: 'hidden',
    position: 'relative',
  },
  heroImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  heroPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroBody: {
    padding: 16,
  },
  productName: {
    fontSize: 20,
    fontWeight: '800',
    color: '#333',
    lineHeight: 26,
  },
  productCode: {
    fontSize: 12,
    color: '#888',
    fontWeight: '600',
    marginTop: 4,
  },
  priceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    gap: 8,
  },
  price: {
    fontSize: 24,
    fontWeight: '800',
    color: ACCENT,
  },
  unitChip: {
    backgroundColor: '#FFF8E8',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  unitChipText: {
    fontSize: 13,
    color: '#666',
    fontWeight: '600',
  },
  stockBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginTop: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    backgroundColor: '#FAFAFA',
    gap: 6,
  },
  stockText: {
    fontSize: 13,
    fontWeight: '700',
  },
  storeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 14,
    borderWidth: 1,
    borderColor: COMPANY_COLORS.primaryBorder,
    marginBottom: 14,
    gap: 10,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
  },
  storeLogo: {
    width: 48,
    height: 48,
    borderRadius: 24,
  },
  storeInfo: {
    flex: 1,
  },
  storeLabel: {
    fontSize: 11,
    color: '#888',
    fontWeight: '600',
  },
  storeName: {
    fontSize: 15,
    fontWeight: '800',
    color: COMPANY_COLORS.primary,
    marginTop: 2,
  },
  storeDesc: {
    fontSize: 12,
    color: '#666',
    marginTop: 2,
  },
  section: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: COMPANY_COLORS.primaryBorder,
    marginBottom: 14,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COMPANY_COLORS.primary,
    marginBottom: 8,
  },
  description: {
    fontSize: 14,
    color: '#444',
    lineHeight: 21,
  },
  observationTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 8,
  },
  observationTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COMPANY_COLORS.primary,
  },
  observationInput: {
    minHeight: 72,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COMPANY_COLORS.primaryBorder,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: '#333',
    textAlignVertical: 'top',
    backgroundColor: COMPANY_COLORS.primarySoft,
  },
  feedbackText: {
    textAlign: 'center',
    marginBottom: 8,
    fontWeight: '600',
    fontSize: 13,
  },
  feedbackOk: {
    color: '#2E7D32',
  },
  feedbackErr: {
    color: '#C62828',
  },
  bottomBar: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  quantityBox: {
    flex: 1,
    maxWidth: 140,
    height: 48,
    borderRadius: 24,
    backgroundColor: ACCENT,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
  },
  quantityButton: {
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quantityButtonDisabled: {
    opacity: 0.45,
  },
  quantityText: {
    color: '#FFF',
    fontSize: 18,
    fontWeight: '700',
  },
  addButton: {
    flex: 1.4,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#222',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  addButtonDisabled: {
    backgroundColor: '#999',
  },
  addButtonText: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '700',
  },
  addButtonPrice: {
    color: '#FFF',
    fontSize: 14,
    fontWeight: '600',
  },
  checkoutFab: {
    position: 'absolute',
    right: 16,
    bottom: 78,
    backgroundColor: '#333',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
  },
  checkoutFabText: {
    color: '#FFF',
    fontWeight: '600',
    fontSize: 12,
  },
  catalogFooter: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 18,
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#EEE',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  catalogStockBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
  },
  catalogStockText: {
    fontSize: 13,
    fontWeight: '700',
  },
  catalogPrice: {
    fontSize: 20,
    fontWeight: '800',
    color: ACCENT,
  },
});
