import { StyleSheet } from 'react-native';
import { CLIENTE_COLORS } from '../../theme/theme';

export const PRIMARY = CLIENTE_COLORS.primary;
export const GOLD = '#F8B125';
export const PAGE_BG = '#F3F5F8';
export const GREEN = '#22A45A';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: PAGE_BG,
  },
  header: {
    backgroundColor: PRIMARY,
    paddingHorizontal: 20,
    paddingBottom: 88,
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 22,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
  },
  brandQuick: {
    color: '#FFF',
    fontSize: 22,
    fontWeight: '800',
  },
  brandStock: {
    color: CLIENTE_COLORS.brandAccent,
    fontSize: 22,
    fontWeight: '800',
  },
  bellButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  greeting: {
    color: '#FFF',
    fontSize: 32,
    fontWeight: '800',
    marginBottom: 6,
  },
  greetingHint: {
    color: 'rgba(255,255,255,0.78)',
    fontSize: 15,
    lineHeight: 22,
    maxWidth: 280,
  },
  content: {
    paddingHorizontal: 16,
    marginTop: -64,
  },
  heroCard: {
    backgroundColor: '#FFF',
    borderRadius: 22,
    padding: 18,
    overflow: 'hidden',
    flexDirection: 'row',
    elevation: 6,
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
  },
  heroCopy: {
    flex: 1,
    paddingRight: 8,
    zIndex: 2,
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: PRIMARY,
    marginBottom: 8,
  },
  heroSubtitle: {
    fontSize: 13,
    color: '#6B7280',
    lineHeight: 18,
    marginBottom: 14,
    maxWidth: 200,
  },
  heroButton: {
    alignSelf: 'flex-start',
    backgroundColor: PRIMARY,
    borderRadius: 16,
    paddingVertical: 8,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  heroButtonText: {
    color: '#FFF',
    fontSize: 13,
    fontWeight: '700',
  },
  section: {
    marginTop: 22,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1F2937',
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  seeAll: {
    color: '#6B7280',
    fontSize: 13,
    fontWeight: '600',
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  actionCard: {
    flex: 1,
    backgroundColor: '#FFF',
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 8,
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  actionIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: CLIENTE_COLORS.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  actionTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: PRIMARY,
    marginBottom: 2,
  },
  actionHint: {
    fontSize: 10,
    color: '#8A93A3',
    textAlign: 'center',
    lineHeight: 13,
  },
  storeCard: {
    backgroundColor: '#FFF',
    borderRadius: 18,
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 5,
    shadowOffset: { width: 0, height: 2 },
  },
  storeCover: {
    width: 72,
    height: 72,
    borderRadius: 14,
    overflow: 'hidden',
  },
  storeCopy: {
    flex: 1,
    marginLeft: 12,
  },
  storeName: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1F2937',
    marginBottom: 2,
  },
  storeHint: {
    fontSize: 12,
    color: '#8A93A3',
    marginBottom: 6,
  },
  storeMeta: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  storeDistance: {
    marginLeft: 4,
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '600',
  },
  openBadge: {
    marginLeft: 10,
    backgroundColor: '#E7F8EE',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
  },
  openBadgeText: {
    color: GREEN,
    fontSize: 11,
    fontWeight: '700',
  },
  emptyStores: {
    color: '#6B7280',
    fontSize: 13,
    paddingVertical: 12,
    textAlign: 'center',
  },
});
