import { StyleSheet } from 'react-native';
import { CLIENTE_COLORS } from '../../theme/theme';

const GOLD = '#F8B125';
const SUCCESS = '#2E7D32';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F4F4F5',
  },
  topGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 260,
  },
  scroll: { flex: 1 },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 36,
  },
  loadingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 15,
    color: '#666',
  },
  errorText: {
    marginTop: 12,
    fontSize: 15,
    color: '#E53935',
    textAlign: 'center',
  },
  retryButton: {
    marginTop: 16,
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: GOLD,
    borderRadius: 12,
  },
  retryButtonText: {
    fontWeight: '700',
    color: '#FFF',
  },
  pedidosTabs: {
    gap: 8,
    paddingBottom: 14,
  },
  pedidoTab: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.85)',
    borderWidth: 1,
    borderColor: 'rgba(248,177,37,0.25)',
  },
  pedidoTabActive: {
    backgroundColor: '#FFF',
    borderColor: GOLD,
  },
  pedidoTabText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#666',
  },
  pedidoTabTextActive: {
    color: GOLD,
  },
  heroCard: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 20,
    marginBottom: 16,
    alignItems: 'center',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(248,177,37,0.15)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
  },
  heroCardSuccess: {
    borderColor: 'rgba(46,125,50,0.2)',
  },
  heroAccentStrip: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 72,
  },
  heroIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 16,
    marginBottom: 14,
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1A1A1A',
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  heroSubtitle: {
    marginTop: 8,
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 8,
  },
  etaBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFF8E7',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    marginTop: 16,
    borderWidth: 1,
    borderColor: 'rgba(248,177,37,0.2)',
    alignSelf: 'stretch',
  },
  etaText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#C77800',
    flex: 1,
  },
  progressWrap: {
    width: '100%',
    marginTop: 18,
  },
  progressTrack: {
    width: '100%',
    height: 5,
    backgroundColor: '#EEEEEE',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: GOLD,
    borderRadius: 3,
  },
  progressFillDone: {
    backgroundColor: SUCCESS,
  },
  progressLabel: {
    marginTop: 6,
    fontSize: 11,
    color: '#999',
    textAlign: 'center',
    fontWeight: '600',
  },
  progressLabelDone: {
    color: SUCCESS,
  },
  heroChipsRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 16,
    width: '100%',
  },
  heroChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: '#F5F5F5',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 10,
  },
  heroChipWide: {
    flex: 1,
  },
  heroChipText: {
    fontSize: 12,
    color: '#555',
    fontWeight: '600',
  },
  card: {
    backgroundColor: '#FFF',
    borderRadius: 18,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#EFEFEF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1A1A',
  },
  timelineWrap: {
    paddingLeft: 2,
  },
  stepRow: {
    flexDirection: 'row',
    minHeight: 56,
  },
  stepIndicatorCol: {
    width: 32,
    alignItems: 'center',
  },
  stepCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#F5F5F5',
    borderWidth: 2,
    borderColor: '#E0E0E0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepCircleDone: {
    backgroundColor: SUCCESS,
    borderColor: SUCCESS,
  },
  stepCircleActive: {
    backgroundColor: '#FFF8E1',
    borderColor: GOLD,
  },
  stepLine: {
    flex: 1,
    width: 2,
    backgroundColor: '#E8E8E8',
    marginVertical: 3,
    borderRadius: 1,
  },
  stepLineDone: {
    backgroundColor: SUCCESS,
  },
  stepContent: {
    flex: 1,
    paddingLeft: 12,
    paddingBottom: 18,
  },
  stepContentLast: {
    paddingBottom: 0,
  },
  stepLabel: {
    fontSize: 14,
    color: '#B0B0B0',
    fontWeight: '500',
  },
  stepLabelDone: {
    color: '#333',
    fontWeight: '600',
  },
  stepLabelActive: {
    color: GOLD,
    fontWeight: '700',
  },
  stepHint: {
    marginTop: 3,
    fontSize: 12,
    color: '#888',
    lineHeight: 17,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 14,
  },
  infoIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#FFF8E7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoTextWrap: { flex: 1 },
  infoLabel: {
    fontSize: 11,
    color: '#999',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  infoText: {
    marginTop: 3,
    fontSize: 14,
    color: '#333',
    lineHeight: 20,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#F0F0F0',
  },
  itemRowLast: {
    borderBottomWidth: 0,
  },
  itemBadge: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#FFF8E7',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  itemBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: GOLD,
  },
  itemInfo: {
    flex: 1,
    paddingRight: 8,
  },
  itemNome: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
  itemDetalhe: {
    marginTop: 2,
    fontSize: 12,
    color: '#888',
  },
  itemSubtotal: {
    fontSize: 14,
    fontWeight: '700',
    color: '#333',
  },
  totalRow: {
    marginTop: 4,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
  },
  totalLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  totalLabel: {
    fontSize: 14,
    color: '#777',
  },
  totalValue: {
    fontSize: 14,
    color: '#777',
  },
  totalLabelBold: {
    fontSize: 16,
    fontWeight: '700',
    color: '#333',
  },
  totalValueBold: {
    fontSize: 16,
    fontWeight: '800',
    color: GOLD,
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
  },
  primaryButton: {
    flex: 1,
    backgroundColor: GOLD,
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonFull: {
    flex: 1,
  },
  primaryButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFF',
  },
  secondaryButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#FFF',
    borderRadius: 14,
    paddingVertical: 15,
    borderWidth: 1.5,
    borderColor: GOLD,
  },
  secondaryButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: GOLD,
  },
});

const PRIMARY = CLIENTE_COLORS.primary;
const PAGE_BG = '#F3F5F8';

export const clientePedidoStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: PAGE_BG },
  header: {
    backgroundColor: PRIMARY,
    paddingHorizontal: 20,
    paddingBottom: 22,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  brandRow: { flex: 1, flexDirection: 'row', alignItems: 'baseline', justifyContent: 'center' },
  brandQuick: { color: '#FFF', fontSize: 20, fontWeight: '800' },
  brandStock: { color: '#1F2937', fontSize: 20, fontWeight: '800' },
  title: { color: '#FFF', fontSize: 24, fontWeight: '800', textAlign: 'center', marginBottom: 6 },
  subtitle: { color: 'rgba(255,255,255,0.75)', fontSize: 13, textAlign: 'center' },
  sheet: { paddingHorizontal: 16, paddingTop: 16 },
  card: { backgroundColor: '#FFF', borderRadius: 22, padding: 16, marginBottom: 12 },
  idRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 },
  code: { fontSize: 18, fontWeight: '800', color: PRIMARY },
  date: { fontSize: 12, color: '#8A93A3', marginTop: 2 },
  stepper: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 8 },
  stepCol: { flex: 1, alignItems: 'center' },
  stepCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#EEF2F7',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  stepCircleDone: { backgroundColor: PRIMARY },
  stepCircleActive: { backgroundColor: '#3B82F6' },
  stepLine: {
    position: 'absolute',
    top: 13,
    left: '50%',
    right: '-50%',
    height: 2,
    backgroundColor: '#E5E7EB',
  },
  stepLineDone: { backgroundColor: PRIMARY },
  stepLabel: { fontSize: 10, color: '#8A93A3', textAlign: 'center', marginTop: 6, fontWeight: '600' },
  stepLabelActive: { color: PRIMARY, fontWeight: '800' },
  storeRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 8 },
  storeIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#EEF2F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  storeName: { fontSize: 15, fontWeight: '800', color: '#1F2937' },
  storeHint: { fontSize: 12, color: '#8A93A3', marginTop: 2 },
  sectionTitle: { fontSize: 15, fontWeight: '800', color: PRIMARY, marginBottom: 10 },
  itemRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 10 },
  itemImage: { width: 44, height: 44, borderRadius: 10, backgroundColor: '#F3F4F6' },
  itemName: { flex: 1, fontSize: 14, fontWeight: '700', color: '#1F2937' },
  itemUnit: { fontSize: 12, color: '#8A93A3', marginTop: 2 },
  itemQty: { fontSize: 12, color: '#6B7280', textAlign: 'right' },
  itemSub: { fontSize: 14, fontWeight: '800', color: PRIMARY, textAlign: 'right' },
  infoRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 6 },
  infoIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: '#EEF2F7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoTitle: { fontSize: 14, fontWeight: '800', color: PRIMARY },
  infoText: { fontSize: 12, color: '#6B7280', marginTop: 2 },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', marginTop: 8 },
  totalLabel: { fontSize: 15, fontWeight: '800', color: PRIMARY },
  totalHint: { fontSize: 12, color: '#8A93A3', marginTop: 2 },
  totalValue: { fontSize: 20, fontWeight: '800', color: PRIMARY },
  helpRow: { flexDirection: 'row', alignItems: 'center', gap: 8, justifyContent: 'center', paddingVertical: 8 },
  helpText: { fontSize: 14, fontWeight: '700', color: PRIMARY },
  chip: { borderRadius: 12, paddingHorizontal: 8, paddingVertical: 4 },
  loadingWrap: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
});
