import { StyleSheet } from 'react-native';
import { COMPANY_COLORS } from '../../theme/theme';

export const styles = StyleSheet.create({
  sectionCard: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
  },
  sectionHeaderCopy: {
    flex: 1,
    marginRight: 12,
  },
  sectionHeaderBlock: {
    marginBottom: 14,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  sectionTitleHero: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COMPANY_COLORS.primary,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COMPANY_COLORS.primary,
  },
  sectionSubtitle: {
    marginTop: 4,
    fontSize: 12,
    color: '#888',
  },
  removeAllText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#D64545',
    marginTop: 4,
  },
  grupoCard: {
    backgroundColor: COMPANY_COLORS.primarySoft,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 6,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COMPANY_COLORS.primaryBorder,
  },
  grupoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 4,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  grupoNomeWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginRight: 8,
  },
  grupoNome: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    color: '#1A1A1A',
  },
  grupoSubtotal: {
    fontSize: 13,
    fontWeight: '700',
    color: '#E89510',
  },
  addressCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COMPANY_COLORS.primarySoft,
    borderRadius: 16,
    padding: 14,
    marginBottom: 0,
    borderWidth: 1,
    borderColor: COMPANY_COLORS.primaryBorder,
    gap: 10,
  },
  addressIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COMPANY_COLORS.primarySoft,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addressInfo: { flex: 1 },
  addressApelido: { fontSize: 14, fontWeight: '700', color: '#333' },
  addressResumo: { fontSize: 12, color: '#666', marginTop: 2 },
  addressCardEmpty: {
    borderColor: COMPANY_COLORS.primary,
    borderStyle: 'dashed',
    backgroundColor: COMPANY_COLORS.primarySoft,
  },
  addressCadastroTitle: { fontSize: 14, fontWeight: '700', color: '#333' },
  addressCadastroHint: { fontSize: 12, color: '#666', marginTop: 2 },
  retryText: { color: COMPANY_COLORS.primary, fontSize: 12, marginBottom: 8, textAlign: 'center' },
  paymentEmptyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COMPANY_COLORS.primarySoft,
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: COMPANY_COLORS.primary,
    borderStyle: 'dashed',
    marginBottom: 16,
    gap: 12,
  },
  paymentEmptyInfo: { flex: 1 },
  paymentEmptyTitle: { fontSize: 14, fontWeight: '700', color: '#333' },
  paymentEmptyHint: { fontSize: 12, color: '#666', marginTop: 2 },
  paymentRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 8,
  },
  paymentChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COMPANY_COLORS.primary,
    backgroundColor: '#FFF',
  },
  paymentChipSelected: {
    backgroundColor: COMPANY_COLORS.primary,
    borderColor: COMPANY_COLORS.primary,
  },
  paymentLabel: { fontSize: 11, fontWeight: '600', color: COMPANY_COLORS.primary },
  paymentLabelSelected: { color: '#FFF' },
  paymentHint: {
    fontSize: 12,
    color: COMPANY_COLORS.primary,
    marginBottom: 12,
    fontWeight: '600',
  },
  summaryCard: {
    backgroundColor: COMPANY_COLORS.primarySoft,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: COMPANY_COLORS.primaryBorder,
    marginBottom: 0,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  summaryLabel: { fontSize: 14, color: '#666' },
  summaryValue: { fontSize: 14, color: '#333' },
  summaryTotalRow: { marginTop: 4, marginBottom: 0, paddingTop: 8, borderTopWidth: 1, borderTopColor: '#EEE' },
  summaryTotalLabel: { fontSize: 16, fontWeight: '700', color: '#333' },
  summaryTotalValue: { fontSize: 18, fontWeight: 'bold', color: COMPANY_COLORS.primary },
  errorText: { color: '#D64545', textAlign: 'center', marginBottom: 8 },
  successText: { color: '#2E7D32', textAlign: 'center', marginBottom: 8 },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 15,
    paddingTop: 8,
    backgroundColor: 'rgba(250,250,250,0.95)',
  },
  submitButton: {
    backgroundColor: '#E89510',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
  },
  submitButtonDisabled: { opacity: 0.7 },
  submitButtonText: { color: '#FFF', fontSize: 15, fontWeight: 'bold' },
  emptyCard: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 16,
    marginTop: 8,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
  },
  emptyHeader: {
    marginBottom: 14,
  },
  emptyKicker: {
    fontSize: 12,
    color: '#888',
    marginBottom: 4,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COMPANY_COLORS.primary,
    marginBottom: 6,
  },
  emptyText: {
    color: '#888',
    fontSize: 12,
    lineHeight: 18,
  },
  emptyAction: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COMPANY_COLORS.primarySoft,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: COMPANY_COLORS.primaryBorder,
  },
  emptyActionLast: {
    marginBottom: 0,
  },
  emptyActionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COMPANY_COLORS.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  emptyActionCopy: {
    flex: 1,
  },
  emptyActionTitle: {
    color: '#333',
    fontWeight: '700',
    fontSize: 13,
  },
  emptyActionHint: {
    marginTop: 2,
    color: '#999',
    fontSize: 11,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    paddingBottom: 32,
  },
  modalTitle: { fontSize: 18, fontWeight: 'bold', color: '#333', marginBottom: 16 },
  modalItem: {
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#EAEAEA',
    marginBottom: 10,
  },
  modalItemSelected: { borderColor: COMPANY_COLORS.primary, backgroundColor: COMPANY_COLORS.primarySoft },
  modalApelido: { fontSize: 14, fontWeight: '700', color: '#333' },
  modalResumo: { fontSize: 12, color: '#666', marginTop: 4 },
  modalClose: { marginTop: 8, alignItems: 'center', paddingVertical: 10 },
  modalCloseText: { color: '#888', fontWeight: '600' },
  modalAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginTop: 4,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: COMPANY_COLORS.primary,
    borderRadius: 12,
  },
  modalAddBtnText: { color: COMPANY_COLORS.primary, fontWeight: '700' },
});
