import { StyleSheet } from 'react-native';
import { CLIENTE_COLORS } from '../../theme/theme';
import { GREEN, PAGE_BG } from '../ClienteHome/styles';

export const PRIMARY = CLIENTE_COLORS.primary;
export const DANGER = '#E23B3B';
export { GREEN };

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: PAGE_BG },
  header: {
    backgroundColor: PRIMARY,
    paddingHorizontal: 20,
    paddingBottom: 22,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
  },
  headerTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  headerSide: { width: 36 },
  brandRow: { flex: 1, flexDirection: 'row', alignItems: 'baseline', justifyContent: 'center' },
  brandQuick: { color: '#FFF', fontSize: 20, fontWeight: '800' },
  brandStock: { color: CLIENTE_COLORS.brandAccent, fontSize: 20, fontWeight: '800' },
  title: { color: '#FFF', fontSize: 26, fontWeight: '800', marginBottom: 4 },
  subtitle: { color: 'rgba(255,255,255,0.85)', fontSize: 14, lineHeight: 20 },
  sheet: { paddingHorizontal: 16, paddingTop: 16 },

  primaryButton: {
    backgroundColor: PRIMARY,
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  primaryButtonText: { color: '#FFF', fontSize: 14, fontWeight: '800' },
  headerButton: {
    alignSelf: 'flex-start',
    marginTop: 14,
    backgroundColor: '#FFF',
    borderRadius: 18,
    paddingVertical: 9,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  headerButtonText: { color: PRIMARY, fontSize: 13, fontWeight: '800' },

  card: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 16,
    marginBottom: 12,
    elevation: 2,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  cardTitle: { fontSize: 16, fontWeight: '800', color: '#1F2937' },
  cardHint: { fontSize: 12, color: '#8A93A3', marginTop: 2 },

  resumoRow: { flexDirection: 'row', marginTop: 12, gap: 8 },
  resumoItem: {
    flex: 1,
    backgroundColor: CLIENTE_COLORS.primarySoft,
    borderRadius: 14,
    paddingVertical: 10,
    alignItems: 'center',
  },
  resumoValor: { fontSize: 18, fontWeight: '800', color: '#1F2937' },
  resumoLabel: { fontSize: 11, color: '#6B7280', marginTop: 2 },

  quiosqueCard: { flexDirection: 'row', alignItems: 'center' },
  quiosqueIcon: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: CLIENTE_COLORS.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  quiosqueCopy: { flex: 1 },
  quiosqueMeta: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 6 },
  chip: {
    backgroundColor: '#F3F5F8',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  chipText: { fontSize: 11, color: '#4B5563', fontWeight: '600' },
  warningChip: { backgroundColor: '#FDECEC' },
  warningChipText: { color: DANGER },

  empty: { alignItems: 'center', paddingVertical: 24, paddingHorizontal: 12 },
  emptyTitle: { fontSize: 16, fontWeight: '800', color: '#1F2937', marginTop: 10, textAlign: 'center' },
  emptyText: {
    fontSize: 13,
    color: '#6B7280',
    textAlign: 'center',
    lineHeight: 19,
    marginTop: 6,
    marginBottom: 16,
  },
  errorText: { color: DANGER, fontSize: 13, textAlign: 'center', marginBottom: 12 },
  retryText: { color: PRIMARY, fontSize: 14, fontWeight: '800' },

  // Formulário
  label: { fontSize: 13, fontWeight: '700', color: '#374151', marginBottom: 6 },
  input: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: '#1F2937',
  },
  inputError: { borderColor: DANGER },
  fieldError: { color: DANGER, fontSize: 12, marginTop: 4 },
  sectionTitle: { fontSize: 16, fontWeight: '800', color: '#1F2937', marginTop: 8, marginBottom: 10 },

  produtoCard: { borderWidth: 1, borderColor: 'transparent' },
  produtoCardError: { borderColor: DANGER },
  produtoTop: { flexDirection: 'row', alignItems: 'center' },
  produtoThumb: { width: 52, height: 52, borderRadius: 12, overflow: 'hidden', marginRight: 12 },
  produtoNome: { fontSize: 15, fontWeight: '800', color: '#1F2937' },
  disponivel: { fontSize: 12, color: GREEN, fontWeight: '700', marginTop: 2 },
  disponivelZero: { color: '#9AA3B2' },
  precoPago: { fontSize: 12, color: '#6B7280', marginTop: 2 },
  produtoInputs: { flexDirection: 'row', gap: 12, marginTop: 12 },
  produtoInputCol: { flex: 1 },
  stepper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 14,
    overflow: 'hidden',
  },
  stepperBtn: {
    width: 38,
    height: 42,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CLIENTE_COLORS.primarySoft,
  },
  stepperInput: { flex: 1, textAlign: 'center', fontSize: 15, fontWeight: '700', color: '#1F2937', paddingVertical: 8 },
  precoInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 14,
    paddingHorizontal: 12,
    height: 44,
  },
  precoPrefix: { fontSize: 14, color: '#6B7280', marginRight: 4 },
  precoInput: { flex: 1, fontSize: 15, fontWeight: '700', color: '#1F2937', paddingVertical: 8 },

  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    backgroundColor: '#FFF',
    borderTopLeftRadius: 22,
    borderTopRightRadius: 22,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 12,
    elevation: 10,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: -3 },
  },
  footerTotals: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  footerLabel: { fontSize: 13, color: '#6B7280' },
  footerValue: { fontSize: 15, fontWeight: '800', color: '#1F2937' },
  saveError: {
    backgroundColor: '#FDECEC',
    color: DANGER,
    fontSize: 13,
    borderRadius: 12,
    padding: 10,
    marginBottom: 10,
    textAlign: 'center',
  },
  buttonDisabled: { opacity: 0.5 },
  deleteButton: { alignItems: 'center', paddingVertical: 14, marginBottom: 8 },
  deleteText: { color: DANGER, fontSize: 14, fontWeight: '800' },
});
