import { StyleSheet } from 'react-native';
import { COMPANY_COLORS } from '../../theme/theme';

export const styles = StyleSheet.create({
  scrollContent: {},
  tabRow: {
    flexDirection: 'row',
    marginHorizontal: 15,
    marginBottom: 16,
    backgroundColor: 'rgba(255,255,255,0.4)',
    borderRadius: 14,
    padding: 4,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 11,
    alignItems: 'center',
  },
  tabBtnActive: {
    backgroundColor: '#FFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  tabBtnText: { color: '#FFF', fontWeight: '700', fontSize: 13 },
  tabBtnTextActive: { color: COMPANY_COLORS.primary },
  stockSection: { paddingHorizontal: 15 },
  statsSection: { paddingHorizontal: 15 },
  datePill: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 6,
    backgroundColor: '#FFF',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(18, 59, 109,0.25)',
  },
  datePillText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#333',
  },
  lucroHero: {
    backgroundColor: '#FFF',
    borderRadius: 18,
    padding: 20,
    marginBottom: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(18, 59, 109,0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  lucroHeroLabel: {
    fontSize: 13,
    color: '#666',
    fontWeight: '600',
    marginBottom: 6,
  },
  lucroHeroValue: {
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  lucroPositivo: { color: '#2E7D32' },
  lucroNegativo: { color: '#D64545' },
  lucroHeroSub: {
    fontSize: 12,
    color: '#888',
    marginTop: 8,
    textAlign: 'center',
  },
  sectionTitleDark: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: 12,
    marginTop: 4,
  },
  resumoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 14,
  },
  resumoCard: {
    width: '48%',
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(18, 59, 109,0.15)',
    borderLeftWidth: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  resumoIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  resumoLabel: { fontSize: 11, color: '#666', marginBottom: 4, fontWeight: '500' },
  resumoValue: { fontSize: 15, fontWeight: '800' },
  movimentosCard: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(18, 59, 109,0.15)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  movimentosTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: 14,
  },
  movimentosEmpty: {
    alignItems: 'center',
    paddingVertical: 24,
    gap: 10,
  },
  movimentosEmptyText: {
    fontSize: 13,
    color: '#888',
    textAlign: 'center',
    paddingHorizontal: 16,
  },
  movimentoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
    gap: 10,
  },
  movimentoIcon: {
    width: 38,
    height: 38,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  movimentoIconVenda: { backgroundColor: '#E8F5E9' },
  movimentoIconCompra: { backgroundColor: '#FFEBEE' },
  movimentoInfo: { flex: 1 },
  movimentoNome: { fontSize: 14, fontWeight: '700', color: '#1A1A1A' },
  movimentoMeta: { fontSize: 11, color: '#888', marginTop: 2 },
  movimentoValores: { alignItems: 'flex-end' },
  movimentoQty: { fontSize: 12, fontWeight: '700' },
  movimentoValor: { fontSize: 13, fontWeight: '700', color: '#333', marginTop: 2 },
  margemPill: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(18, 59, 109,0.15)',
  },
  margemText: { fontSize: 14, fontWeight: '700', color: '#2E7D32' },
  margemSub: { fontSize: 12, color: '#666', marginTop: 4 },
  chartBlock: {
    backgroundColor: '#FFF',
    borderRadius: 16,
    padding: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: 'rgba(18, 59, 109,0.15)',
  },
  chartBlockTitle: { fontSize: 15, fontWeight: '700', color: '#1A1A1A', marginBottom: 12 },
  barChartRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    height: 120,
  },
  barColumn: { flex: 1, alignItems: 'center', marginHorizontal: 2 },
  bar: { width: '70%', backgroundColor: COMPANY_COLORS.primary, borderRadius: 6, minHeight: 8 },
  barLabel: { fontSize: 10, color: '#666', marginTop: 6 },
  barValue: { fontSize: 9, color: '#999', marginTop: 2 },
  pagamentoRow: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(18, 59, 109,0.15)',
  },
  pagamentoLeft: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  pagamentoIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: COMPANY_COLORS.primarySoft,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pagamentoInfo: { marginLeft: 10, flex: 1 },
  pagamentoLabel: { fontSize: 14, fontWeight: '600', color: '#333' },
  pagamentoValor: { fontSize: 12, color: '#666', marginTop: 2 },
  pagamentoBarBg: { height: 8, backgroundColor: '#F0F0F0', borderRadius: 4, overflow: 'hidden' },
  pagamentoBarFill: { height: '100%', backgroundColor: COMPANY_COLORS.primary, borderRadius: 4 },
  pagamentoPct: { fontSize: 12, fontWeight: '700', color: COMPANY_COLORS.primary, marginTop: 4, textAlign: 'right' },
  pagamentoEmpty: { fontSize: 13, color: '#999', marginBottom: 12 },
  centerBox: { alignItems: 'center', paddingVertical: 40, paddingHorizontal: 24, gap: 10 },
  loadingHint: { fontSize: 13, color: '#666' },
  errorText: { color: '#D64545', textAlign: 'center' },
  retryBtn: { marginTop: 4 },
  retryText: { color: COMPANY_COLORS.primary, fontWeight: '700' },
  emptyText: { color: '#666', textAlign: 'center' },
});
